CREATE TABLE PEOPLE
   (	ID VARCHAR2(20) NOT NULL ENABLE,
	NAME NUMBER(12,2),
	EMAIL VARCHAR2(100),
	ADDRESS VARCHAR2(100) NOT NULL ENABLE,
	 CONSTRAINT PEOPLE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE
   ) ;

